<?php
    //Config
    $langcode = "en";
    $observer_code = "observer";

    //Localization
    $lang = array(
        "en" => array(
            "todo" => "TO-DO",
            "in_progress" => "In Progress",
            "done" => "Done",
            "task_value" => "Task Value",
            "edit_task" => "Edit Task",
            "edit" => "Edit",
            "cancel" => "Cancel",
            "settings" => "Settings",
            "logout" => "Logout",
            "announcements" => "Announcements",
            "time" => "Time",
            "message" => "Messsage",
            "username" => "Username",
            "password" => "Password",
            "login" => "Login",
            "settings" => "Settings",
            "task_board" => "Task Board",
            "save" => "Save",
            "user" => "User",
            "status" => "Status",
            "database_created" => "Database created!",
            "database_already_created" => "Database already created.",
            "announcement_placeholder" => "Announcement text...",
            "add" => "Add",
            "events" => "Events",
            "remove" => "Remove",
        ),
        "tr" => array(
            "todo" => "Yapılacaklar",
            "in_progress" => "Devam Ediyor",
            "done" => "Bitti",
            "task_value" => "Görev içeriği",
            "edit_task" => "Görevi Düzenle",
            "edit" => "Düzenle",
            "cancel" => "İptal Et",
            "settings" => "Ayarlar",
            "logout" => "Çıkış yap",
            "announcements" => "Duyurular",
            "time" => "Zaman",
            "message" => "Mesaj",
            "username" => "Kullanıcı Adı",
            "password" => "Şifre",
            "login" => "Giriş yap",
            "settings" => "Ayarlar",
            "task_board" => "Görev Panosu",
            "save" => "Kaydet",
            "user" => "Kullanıcı",
            "status" => "Durum",
            "database_created" => "Veritabanı oluşturuldu!",
            "database_already_created" => "Veritabanı zaten oluşturulmuş.",
            "announcement_placeholder" => "Duyuru metni...",
            "add" => "Ekle",
            "events" => "Olaylar",
            "remove" => "Sil",
        )
    );
?>