<?php
    $lang = array(
        "todo" => "TO-DO",
        "in_progress" => "In Progress",
        "done" => "Done",
        "task_value" => "Task Value",
        "edit_task" => "Edit Task",
        "edit" => "Edit",
        "cancel" => "Cancel",
        "settings" => "Settings",
        "logout" => "Logout",
        "announcements" => "Announcements",
        "time" => "Time",
        "message" => "Messsage",
        "username" => "Username",
        "password" => "Password",
        "login" => "Login",
        "settings" => "Settings",
        "task_board" => "Task Board",
        "save" => "Save",
        "user" => "User",
        "status" => "Status",
        "database_created" => "Database created!",
        "database_already_created" => "Database already created.",
        "announcement_placeholder" => "Announcement text...",
        "add" => "Add",
        "events" => "Events",
        "remove" => "Remove",
    );
?>
