<?php
    $lang = array(
        "todo" => "Yapılacaklar",
        "in_progress" => "Devam Ediyor",
        "done" => "Bitti",
        "task_value" => "Görev içeriği",
        "edit_task" => "Görevi Düzenle",
        "edit" => "Düzenle",
        "cancel" => "İptal Et",
        "settings" => "Ayarlar",
        "logout" => "Çıkış yap",
        "announcements" => "Duyurular",
        "time" => "Zaman",
        "message" => "Mesaj",
        "username" => "Kullanıcı Adı",
        "password" => "Şifre",
        "login" => "Giriş yap",
        "settings" => "Ayarlar",
        "task_board" => "Görev Panosu",
        "save" => "Kaydet",
        "user" => "Kullanıcı",
        "status" => "Durum",
        "database_created" => "Veritabanı oluşturuldu!",
        "database_already_created" => "Veritabanı zaten oluşturulmuş.",
        "announcement_placeholder" => "Duyuru metni...",
        "add" => "Ekle",
        "events" => "Olaylar",
        "remove" => "Sil",
    );
?>
